# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destino', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category'),
        ),
        migrations.AlterField(
            model_name='destino',
            name='imagen',
            field=models.ImageField(upload_to='media/pais/'),
        ),
    ]
