# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('destino', '0002_auto_20160219_1802'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='destino',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='destino',
            name='rating',
            field=models.IntegerField(blank=True, default=5),
            preserve_default=False,
        ),
    ]
