# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 00:35
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('destino', '0003_auto_20160222_0015'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='destino',
            managers=[
                ('mexico', django.db.models.manager.Manager()),
            ],
        ),
    ]
