# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Aerolinea', '0001_initial'),
        ('usuario', '0002_myuser_perfil'),
        ('destino', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelo',
            name='destino',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='destino.Destino'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuario.MyUser'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='vuelo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Aerolinea.Vuelo'),
        ),
    ]
