# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aerolinea', '0002_auto_20160219_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.MyUser'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='vuelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aerolinea.Vuelo'),
        ),
    ]
