# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Aerolinea', '0003_auto_20160219_1802'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='aerolinea',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destino.Destino'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
